version: '3'
services:
  app:
    image: sample
    build: ./sampleapp
    container_name: sample
    restart: always

  e2e:
    image: tests
    build: ./e2e
    container_name: tests
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:5000
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json